name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "ci"
          make install_dev
          make isort_check
          make lint
          make test
